/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResponse"];
                        "application/json": components["schemas"]["LoginResponse"];
                        "text/json": components["schemas"]["LoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ContactDto"][];
                        "application/json": components["schemas"]["ContactDto"][];
                        "text/json": components["schemas"]["ContactDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateContactRequest"];
                    "text/json": components["schemas"]["CreateContactRequest"];
                    "application/*+json": components["schemas"]["CreateContactRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ContactDto"];
                        "application/json": components["schemas"]["ContactDto"];
                        "text/json": components["schemas"]["ContactDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/field-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    entityType?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FieldDefinitionDto"][];
                        "application/json": components["schemas"]["FieldDefinitionDto"][];
                        "text/json": components["schemas"]["FieldDefinitionDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateFieldDefinitionRequest"];
                    "text/json": components["schemas"]["CreateFieldDefinitionRequest"];
                    "application/*+json": components["schemas"]["CreateFieldDefinitionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FieldDefinitionDto"];
                        "application/json": components["schemas"]["FieldDefinitionDto"];
                        "text/json": components["schemas"]["FieldDefinitionDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/field-definitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateFieldDefinitionRequest"];
                    "text/json": components["schemas"]["UpdateFieldDefinitionRequest"];
                    "application/*+json": components["schemas"]["UpdateFieldDefinitionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FieldDefinitionDto"];
                        "application/json": components["schemas"]["FieldDefinitionDto"];
                        "text/json": components["schemas"]["FieldDefinitionDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["JobStatusResponse"];
                        "application/json": components["schemas"]["JobStatusResponse"];
                        "text/json": components["schemas"]["JobStatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PipelineBoardDto"];
                        "application/json": components["schemas"]["PipelineBoardDto"];
                        "text/json": components["schemas"]["PipelineBoardDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{dealId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    dealId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MoveDealRequest"];
                    "text/json": components["schemas"]["MoveDealRequest"];
                    "application/*+json": components["schemas"]["MoveDealRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{dealId}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    dealId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ScoreDealResponse"];
                        "application/json": components["schemas"]["ScoreDealResponse"];
                        "text/json": components["schemas"]["ScoreDealResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{dealId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    dealId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DealDetailDto"];
                        "application/json": components["schemas"]["DealDetailDto"];
                        "text/json": components["schemas"]["DealDetailDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{dealId}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    dealId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LogActivityRequest"];
                    "text/json": components["schemas"]["LogActivityRequest"];
                    "application/*+json": components["schemas"]["LogActivityRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkspaceSettingsDto"];
                        "application/json": components["schemas"]["WorkspaceSettingsDto"];
                        "text/json": components["schemas"]["WorkspaceSettingsDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateWorkspaceSettingsRequest"];
                    "text/json": components["schemas"]["UpdateWorkspaceSettingsRequest"];
                    "application/*+json": components["schemas"]["UpdateWorkspaceSettingsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkspaceSettingsDto"];
                        "application/json": components["schemas"]["WorkspaceSettingsDto"];
                        "text/json": components["schemas"]["WorkspaceSettingsDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivityDto: {
            id: string;
            type: string;
            body: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        ContactDto: {
            id: string;
            firstName: null | string;
            lastName: null | string;
            email: null | string;
            companyName: null | string;
            lifecycleStage: string;
            customFields: Record<string, never>;
        };
        CreateContactRequest: {
            firstName: string;
            lastName: null | string;
            email: null | string;
            companyName: null | string;
            customFields?: null | Record<string, never>;
        };
        CreateFieldDefinitionRequest: {
            entityType: string;
            key: string;
            label: string;
            fieldType: string;
            options: null | string[];
            required: boolean;
            /** Format: int32 */
            order: number | string;
        };
        DealCardDto: {
            id: string;
            title: string;
            /** Format: int32 */
            amountCents: null | number | string;
            currency: null | string;
            /** Format: int32 */
            aiScore: null | number | string;
            aiScoreRationale: null | string;
        };
        DealDetailDto: {
            id: string;
            title: string;
            stageName: string;
            /** Format: int32 */
            amountCents: null | number | string;
            currency: null | string;
            /** Format: int32 */
            aiScore: null | number | string;
            aiScoreRationale: null | string;
            contactNames: string[];
            activities: components["schemas"]["ActivityDto"][];
        };
        FieldDefinitionDto: {
            id: string;
            entityType: string;
            key: string;
            label: string;
            fieldType: string;
            options: null | string[];
            required: boolean;
            /** Format: int32 */
            order: number | string;
        };
        JobStatusResponse: {
            status: string;
            lastError: null | string;
        };
        LogActivityRequest: {
            type: string;
            body: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        LoginResponse: {
            token: string;
            workspaceId: string;
            workspaceName: string;
        };
        MoveDealRequest: {
            stageId: string;
        };
        PipelineBoardDto: {
            id: string;
            name: string;
            stages: components["schemas"]["StageDto"][];
        };
        ScoreDealResponse: {
            jobId: string;
        };
        StageDto: {
            id: string;
            name: string;
            deals: components["schemas"]["DealCardDto"][];
        };
        UpdateFieldDefinitionRequest: {
            label: string;
            options: null | string[];
            required: boolean;
            /** Format: int32 */
            order: number | string;
        };
        UpdateWorkspaceSettingsRequest: {
            terminology: null | Record<string, never>;
            enabledModules: null | string[];
        };
        WorkspaceSettingsDto: {
            terminology: Record<string, never>;
            enabledModules: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
