/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResponse"];
                        "application/json": components["schemas"]["LoginResponse"];
                        "text/json": components["schemas"]["LoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GoogleExchangeRequest"];
                    "text/json": components["schemas"]["GoogleExchangeRequest"];
                    "application/*+json": components["schemas"]["GoogleExchangeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResponse"];
                        "application/json": components["schemas"]["LoginResponse"];
                        "text/json": components["schemas"]["LoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CompanyDto"][];
                        "application/json": components["schemas"]["CompanyDto"][];
                        "text/json": components["schemas"]["CompanyDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CompanyDto"];
                        "application/json": components["schemas"]["CompanyDto"];
                        "text/json": components["schemas"]["CompanyDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCompanyRequest"];
                    "text/json": components["schemas"]["UpdateCompanyRequest"];
                    "application/*+json": components["schemas"]["UpdateCompanyRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CompanyDto"];
                        "application/json": components["schemas"]["CompanyDto"];
                        "text/json": components["schemas"]["CompanyDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                    lifecycleStage?: string;
                    sort?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ContactDto"][];
                        "application/json": components["schemas"]["ContactDto"][];
                        "text/json": components["schemas"]["ContactDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateContactRequest"];
                    "text/json": components["schemas"]["CreateContactRequest"];
                    "application/*+json": components["schemas"]["CreateContactRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ContactDto"];
                        "application/json": components["schemas"]["ContactDto"];
                        "text/json": components["schemas"]["ContactDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contacts/import/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CsvImportPreviewRequest"];
                    "text/json": components["schemas"]["CsvImportPreviewRequest"];
                    "application/*+json": components["schemas"]["CsvImportPreviewRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CsvImportPreviewResponse"];
                        "application/json": components["schemas"]["CsvImportPreviewResponse"];
                        "text/json": components["schemas"]["CsvImportPreviewResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contacts/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CsvImportRequest"];
                    "text/json": components["schemas"]["CsvImportRequest"];
                    "application/*+json": components["schemas"]["CsvImportRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CsvImportResponse"];
                        "application/json": components["schemas"]["CsvImportResponse"];
                        "text/json": components["schemas"]["CsvImportResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/field-definitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    entityType?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FieldDefinitionDto"][];
                        "application/json": components["schemas"]["FieldDefinitionDto"][];
                        "text/json": components["schemas"]["FieldDefinitionDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateFieldDefinitionRequest"];
                    "text/json": components["schemas"]["CreateFieldDefinitionRequest"];
                    "application/*+json": components["schemas"]["CreateFieldDefinitionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FieldDefinitionDto"];
                        "application/json": components["schemas"]["FieldDefinitionDto"];
                        "text/json": components["schemas"]["FieldDefinitionDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/field-definitions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateFieldDefinitionRequest"];
                    "text/json": components["schemas"]["UpdateFieldDefinitionRequest"];
                    "application/*+json": components["schemas"]["UpdateFieldDefinitionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["FieldDefinitionDto"];
                        "application/json": components["schemas"]["FieldDefinitionDto"];
                        "text/json": components["schemas"]["FieldDefinitionDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["JobStatusResponse"];
                        "application/json": components["schemas"]["JobStatusResponse"];
                        "text/json": components["schemas"]["JobStatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    unreadOnly?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NotificationDto"][];
                        "application/json": components["schemas"]["NotificationDto"][];
                        "text/json": components["schemas"]["NotificationDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UnreadCountResponse"];
                        "application/json": components["schemas"]["UnreadCountResponse"];
                        "text/json": components["schemas"]["UnreadCountResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PipelineBoardDto"];
                        "application/json": components["schemas"]["PipelineBoardDto"];
                        "text/json": components["schemas"]["PipelineBoardDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{dealId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    dealId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MoveDealRequest"];
                    "text/json": components["schemas"]["MoveDealRequest"];
                    "application/*+json": components["schemas"]["MoveDealRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{dealId}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    dealId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ScoreDealResponse"];
                        "application/json": components["schemas"]["ScoreDealResponse"];
                        "text/json": components["schemas"]["ScoreDealResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{dealId}/draft-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    dealId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DraftEmailRequest"];
                    "text/json": components["schemas"]["DraftEmailRequest"];
                    "application/*+json": components["schemas"]["DraftEmailRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EmailDraftResponse"];
                        "application/json": components["schemas"]["EmailDraftResponse"];
                        "text/json": components["schemas"]["EmailDraftResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{dealId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    dealId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DealDetailDto"];
                        "application/json": components["schemas"]["DealDetailDto"];
                        "text/json": components["schemas"]["DealDetailDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    dealId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateDealRequest"];
                    "text/json": components["schemas"]["UpdateDealRequest"];
                    "application/*+json": components["schemas"]["UpdateDealRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DealDetailDto"];
                        "application/json": components["schemas"]["DealDetailDto"];
                        "text/json": components["schemas"]["DealDetailDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{dealId}/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    dealId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SummarizeDealResponse"];
                        "application/json": components["schemas"]["SummarizeDealResponse"];
                        "text/json": components["schemas"]["SummarizeDealResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{dealId}/next-best-action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    dealId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["NextBestActionResponse"];
                        "application/json": components["schemas"]["NextBestActionResponse"];
                        "text/json": components["schemas"]["NextBestActionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{dealId}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    dealId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LogActivityRequest"];
                    "text/json": components["schemas"]["LogActivityRequest"];
                    "application/*+json": components["schemas"]["LogActivityRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ReportsResponse"];
                        "application/json": components["schemas"]["ReportsResponse"];
                        "text/json": components["schemas"]["ReportsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RefreshReportsResponse"];
                        "application/json": components["schemas"]["RefreshReportsResponse"];
                        "text/json": components["schemas"]["RefreshReportsResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    type?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saved-views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    entityType?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SavedViewDto"][];
                        "application/json": components["schemas"]["SavedViewDto"][];
                        "text/json": components["schemas"]["SavedViewDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateSavedViewRequest"];
                    "text/json": components["schemas"]["CreateSavedViewRequest"];
                    "application/*+json": components["schemas"]["CreateSavedViewRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SavedViewDto"];
                        "application/json": components["schemas"]["SavedViewDto"];
                        "text/json": components["schemas"]["SavedViewDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/saved-views/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SearchResultsDto"];
                        "application/json": components["schemas"]["SearchResultsDto"];
                        "text/json": components["schemas"]["SearchResultsDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    dealId?: string;
                    contactId?: string;
                    companyId?: string;
                    includeCompleted?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskDto"][];
                        "application/json": components["schemas"]["TaskDto"][];
                        "text/json": components["schemas"]["TaskDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTaskRequest"];
                    "text/json": components["schemas"]["CreateTaskRequest"];
                    "application/*+json": components["schemas"]["CreateTaskRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskDto"];
                        "application/json": components["schemas"]["TaskDto"];
                        "text/json": components["schemas"]["TaskDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateTaskRequest"];
                    "text/json": components["schemas"]["UpdateTaskRequest"];
                    "application/*+json": components["schemas"]["UpdateTaskRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TaskDto"];
                        "application/json": components["schemas"]["TaskDto"];
                        "text/json": components["schemas"]["TaskDto"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkspaceSettingsDto"];
                        "application/json": components["schemas"]["WorkspaceSettingsDto"];
                        "text/json": components["schemas"]["WorkspaceSettingsDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateWorkspaceSettingsRequest"];
                    "text/json": components["schemas"]["UpdateWorkspaceSettingsRequest"];
                    "application/*+json": components["schemas"]["UpdateWorkspaceSettingsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkspaceSettingsDto"];
                        "application/json": components["schemas"]["WorkspaceSettingsDto"];
                        "text/json": components["schemas"]["WorkspaceSettingsDto"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivityDto: {
            id: string;
            type: string;
            body: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        ActivityReportRow: {
            /** Format: date */
            date: string;
            type: string;
            /** Format: int32 */
            count: number | string;
        };
        CompanyDto: {
            id: string;
            name: string;
            domain: null | string;
            customFields: Record<string, never>;
        };
        ContactDto: {
            id: string;
            firstName: null | string;
            lastName: null | string;
            email: null | string;
            companyName: null | string;
            lifecycleStage: string;
            customFields: Record<string, never>;
        };
        CreateContactRequest: {
            firstName: string;
            lastName: null | string;
            email: null | string;
            companyName: null | string;
            customFields?: null | Record<string, never>;
        };
        CreateFieldDefinitionRequest: {
            entityType: string;
            key: string;
            label: string;
            fieldType: string;
            options: null | string[];
            required: boolean;
            /** Format: int32 */
            order: number | string;
        };
        CreateSavedViewRequest: {
            entityType: string;
            name: string;
            queryString: string;
        };
        CreateTaskRequest: {
            title: string;
            /** Format: date-time */
            dueAt: null | string;
            contactId: null | string;
            companyId: null | string;
            dealId: null | string;
        };
        CsvImportPreviewRequest: {
            csvContent: string;
        };
        CsvImportPreviewResponse: {
            headers: string[];
            previewRows: {
                [key: string]: string;
            }[];
            /** Format: int32 */
            totalRows: number | string;
        };
        CsvImportRequest: {
            csvContent: string;
            columnMapping: {
                [key: string]: string;
            };
        };
        CsvImportResponse: {
            jobId: string;
        };
        DealCardDto: {
            id: string;
            title: string;
            /** Format: int32 */
            amountCents: null | number | string;
            currency: null | string;
            /** Format: int32 */
            aiScore: null | number | string;
            aiScoreRationale: null | string;
        };
        DealDetailDto: {
            id: string;
            title: string;
            stageName: string;
            /** Format: int32 */
            amountCents: null | number | string;
            currency: null | string;
            forecastCategory: string;
            /** Format: int32 */
            aiScore: null | number | string;
            aiScoreRationale: null | string;
            aiSummary: null | string;
            /** Format: date-time */
            aiSummarizedAt: null | string;
            /** Format: int32 */
            activitiesSinceSummary: number | string;
            contactNames: string[];
            activities: components["schemas"]["ActivityDto"][];
            customFields: Record<string, never>;
        };
        DraftEmailRequest: {
            instruction: null | string;
        };
        EmailDraftResponse: {
            jobId: string;
        };
        FieldDefinitionDto: {
            id: string;
            entityType: string;
            key: string;
            label: string;
            fieldType: string;
            options: null | string[];
            required: boolean;
            /** Format: int32 */
            order: number | string;
        };
        ForecastReportRow: {
            forecastCategory: string;
            /** Format: int32 */
            dealCount: number | string;
            /** Format: int32 */
            dealValueCents: number | string;
            /** Format: int32 */
            weightedValueCents: number | string;
        };
        GoogleExchangeRequest: {
            code: string;
        };
        JobStatusResponse: {
            status: string;
            lastError: null | string;
            result: null | string;
        };
        LogActivityRequest: {
            type: string;
            body: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        LoginResponse: {
            token: string;
            workspaceId: string;
            workspaceName: string;
        };
        MoveDealRequest: {
            stageId: string;
        };
        NextBestActionResponse: {
            jobId: string;
        };
        NotificationDto: {
            id: string;
            type: string;
            entityType: null | string;
            entityId: null | string;
            /** Format: date-time */
            readAt: null | string;
            /** Format: date-time */
            createdAt: string;
        };
        PipelineBoardDto: {
            id: string;
            name: string;
            stages: components["schemas"]["StageDto"][];
        };
        PipelineReportRow: {
            stageId: string;
            stageName: string;
            /** Format: int32 */
            dealCount: number | string;
            /** Format: int32 */
            dealValueCents: number | string;
            /** Format: int32 */
            weightedValueCents: number | string;
        };
        RefreshReportsResponse: {
            jobId: string;
        };
        ReportsResponse: {
            dealTerm: string;
            dealTermPlural: string;
            pipeline: components["schemas"]["PipelineReportRow"][];
            forecast: components["schemas"]["ForecastReportRow"][];
            activity: components["schemas"]["ActivityReportRow"][];
            /** Format: date-time */
            refreshedAt: null | string;
        };
        SavedViewDto: {
            id: string;
            entityType: string;
            name: string;
            queryString: string;
            /** Format: date-time */
            createdAt: string;
        };
        ScoreDealResponse: {
            jobId: string;
        };
        SearchResultDto: {
            id: string;
            label: string;
            sublabel: null | string;
        };
        SearchResultsDto: {
            contacts: components["schemas"]["SearchResultDto"][];
            companies: components["schemas"]["SearchResultDto"][];
            deals: components["schemas"]["SearchResultDto"][];
        };
        StageDto: {
            id: string;
            name: string;
            deals: components["schemas"]["DealCardDto"][];
        };
        SummarizeDealResponse: {
            jobId: string;
        };
        TaskDto: {
            id: string;
            title: string;
            /** Format: date-time */
            dueAt: null | string;
            /** Format: date-time */
            completedAt: null | string;
            aiSuggested: boolean;
            contactId: null | string;
            companyId: null | string;
            dealId: null | string;
        };
        UnreadCountResponse: {
            /** Format: int32 */
            count: number | string;
        };
        UpdateCompanyRequest: {
            name: string;
            domain: null | string;
            customFields: null | Record<string, never>;
        };
        UpdateDealRequest: {
            /** Format: int32 */
            amountCents: null | number | string;
            currency: null | string;
            forecastCategory: string;
            customFields: null | Record<string, never>;
        };
        UpdateFieldDefinitionRequest: {
            label: string;
            options: null | string[];
            required: boolean;
            /** Format: int32 */
            order: number | string;
        };
        UpdateTaskRequest: {
            title: string;
            /** Format: date-time */
            dueAt: null | string;
            completed: boolean;
        };
        UpdateWorkspaceSettingsRequest: {
            terminology: null | Record<string, never>;
            enabledModules: null | string[];
        };
        WorkspaceSettingsDto: {
            terminology: Record<string, never>;
            enabledModules: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
